<template>
  <div class="m-6 sm:mx-16 md:mx-24 lg:mx-32 xl:mx-40 2xl:mx-48">
    <InfoElement
      :value="'Regulamin serwisu OKKI'"
      :icon="'M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253'"
    />
    <div class="rodo-div mt-8 bg-white p-5 shadow-md text-gray-600">
      <h1 class="text-xl font-bold">Korzystanie z serwisu jest jednoznaczne z akceptacją poniższego regulaminu. Nieznajomość regulaminu nie zwalnia z odpowiedzialności.</h1>
      <ol class="list-roman">
        <li><h2>Pojęcia ogólne</h2><ul><li><strong>Regulamin</strong> - niniejszy regulamin</li><li><strong>Serwis</strong> - serwis internetowy <q>OKKI</q>, działający pod adresem https://okki.herokuapp.com/</li><li><strong>Usługodawca</strong> - właściciel serwisu będący osobą fizyczną - Stanisław Sztrajt, Kordian Janowski</li><li><strong>Usługobiorca</strong> - każda osoba fizyczna, uzyskująca dostęp do Serwisu i korzystająca z usług świadczonych za pośrednictwem Serwisu przez Usługodawcę.</li></ul></li>
        <li><h2>Warunki używania Serwisu</h2><ul><li>Używanie Serwisu przez każdego z Usługobiorców jest nieodpłatne i dobrowolne.</li><li>Usługobiorcy mają obowiązek zapoznania się z Regulaminem oraz pozostałymi dokumentami stanowiącymi jego integralną część i muszą zaakceptować w całości jego postanowienia w celu dalszego korzystania z Serwisu.</li><li>Usługobiorcy nie mogą wykorzystywać żadnych pozyskanych w Serwisie danych osobowych do celów marketingowych.</li><li>Zabrania się działań wykonywanych osobiście przez Usługobiorców lub przy użyciu oprorgamowania:<ul><li>bez zgody pisemnej, dekompilacji i analizy kodu źródłowego,</li><li>bez zgody pisemnej, powodujących nadmierne obciążenie serwera Serwisu,</li><li>bez zgody pisemnej, prób wykrycia luk w zabezpieczeniach Serwisu i konfiguracji serwera,</li><li>podejmowania prób wgrywania lub wszczykiwania na serwer i do bazy danych kodu, skryptów i oprogramowania mogących wyrządzić szkodę oprogramowaniu Serwisu, innym Usługobiorcom lub Usługodawcy,</li><li>podejmowania prób wgrywania lub wszczykiwania na serwer i do bazy danych kodu, skryptów i oprogramowania mogących śledzić lub wykradać dane Usługobiorców lub Usługodawcy,</li><li>podejmowania jakichkolwiek działań mających na celu uszkodzenie, zablokowanie działania Serwisu lub uniemożliwienie realizacji celu w jakim działa Serwis.</li></ul></li><li>W przypadku wykrycia zaistnienia lub potencjalnej możliwości zaistnienia incydentu Cyberbezpieczeństwa lub naruszenia RODO, Usługobiorcy w pierwszej kolejności powinni zgłosić ten fakt Usługodawcy w celu szybkiego usunięcia problemu / zagrożenia i zabezpieczenia interesów wszystkich Usługobiorców Serwisu.</li></ul></li>
        <li><h2>Warunki oraz zasady rejestracji</h2><ul><li>Usługobiorcy mogą korzystać z Serwisu bez konieczności rejestracji.</li><li>Usługobiorcy muszą być zarejestrowani i posiadać konto w Serwisie by korzystać z dodatkowych usług świadczonych w Serwisie, dostępnych jedynie dla Usługobiorców po zalogowaniu.</li><li>Rejestracja w Serwisie jest dobrowolna.</li><li>Rejestracja w Serwisie jest nieodpłatna.</li><li>Każdy Usługobiorca może posiadać tylko jedno konto w Serwisie.</li> <li>Wymagania techniczne związane z rejestracją konta:<ul><li>posiadanie indywidualnego konta poczty elektronicznej e-mail,</li></ul></li><li>Rejestrujący się w Serwisie Usługobiorcy wyrażają zgodę na przetwarzanie ich danych osobowych przez Usługobiorcę w zakresie w jakim zostały one wprowadzone do Serwisu podczas procesu rejestracji oraz ich późniejszych zmianom lub usunięciu.</li><li>Usługodawca ma prawo zawieszać lub usuwać konta Usługobiorców według własnego uznania, uniemożliwiając lub ograniczając w ten sposób dostęp do poszczególnych lub wszystkich usług, treści, materiałów i zasobów Serwisu, w szczególności jeżeli Usługobiorca dopuści się łamania Regulaminu, powszechnie obowiązujących przepisów prawa, zasad współżycia społecznego lub działa na szkodę Usługodawcy lub innych Usługobiorców, uzasadnionego interesu Usługodawcy oraz podmiotów trzecich współpracujących lub nie z Usługodawcą.</li><li>Wszelkie usługi Serwisu mogą być zmieniane co do ich treści i zakresu, dodawane lub odejmowane, a także czasowo zawieszane lub dostęp do nich może być ograniczany, według swobodnej decyzji Usługodawcy, bez możliwości wnoszenia sprzeciwu w tym zakresie przez Usługobiorców.</li><li>Dodatkowe zasady bezpieczeństwa w zakresie korzystania z konta:<ul><li>Zabrania się Usługobiorcom zarejestrowanym w Serwisie do udostępniania loginu oraz hasła do swojego konta osobom trzecim.</li><li>Usługodawca nie ma prawa i nigdy nie będzie zażądać od Usługobiorcy hasła do wybranego konta.</li></ul></li><li>Usuwanie konta:<ul><li>Każdy Usługobiorca posiadający konto w Serwisie ma możliwość samodzielnego usunięcia konta z Serwisu.</li><li>Usługobiorcy mogą to uczynić po zalogowaniu się w panelu w Serwisie.</li><li>Usunięcie konta skutkuje usunięciem wszelkich danych identyfikacyjnych Usługobiorcy oraz anonimizacją nazwy użytkownika i adresu e-mail.</li></ul></li></ul></li>
        <li><h2>Warunki komunikacji i świadczenia pozostałych usług w Serwisie</h2><ul><li>Serwis udostępnia usługi i narzędzia umożliwiające Usługobiorcom interakcję z Serwisem w postaci:<ul><li>Formularz kontaktowy</li><li>Komentowania ogłoszeń</li><li>Publikowania własnych treści w postaci ogłoszeń</li></ul></li><li>Serwis udostępnia dane kontaktowe w postaci:<ul><li>Adresu e-mail</li></ul></li><li>W przypadku kontaktu Usługobiorcy z Usługodawcą, dane osobowe Usługobiorców będa przetwarzane zgodnie z <router-link to="/privacy-policy" class="rodo-link">Polityką Prywatności</router-link>, stanowiącą integralną część Regulaminu.</li><li>Warunki umieszczania treści przez Usługobiorców w Serwisie:<ul><li>Zabrania się umieszczania w Serwisie treści obraźliwych lub oszczerczych względem Usługodawcy, pozostałych Usługobiorców, osób trzecich oraz podmiotów trzecich,</li><li>Zabrania się umieszczania w Serwisie materiałów tekstowcyh, graficznych, audiowizualnych, skryptów, programów i innych utworów, na które Usługobiorca nie posiada się licencji, lub których autor praw majątkowych nie wyraził zgody na darmową publikację,</li><li>Zabrania się umieszczania w Serwisie treści wulgarnych, pornograficznych, erotycznych i niezgodnych z polskim i europejskim prawem a także odnośników do stron zawierających wskazane treści,</li><li>Zabrania się umieszczania w Serwisie skryptów i programów nadmiernie obciążających serwer, oprogramowania nielegalnego, oprogramowania służącego do naruszania zabezpieczeń oraz innych podobnych działań a także odnośników do stron zawierających wskazane materiały,</li><li>Zabrania się umieszczania w Serwisie treści merketingowych i reklamujących inne serwisy komercyjne, produkty, usługi czy komercyjne strony internetowe</li></ul></li></ul></li>
        <li><h2>Gromadzenie danych o Usługobiorcach</h2><p>W celu prawidłowego świadczenia usług przez Serwis, zabezpieczenia prawnego interesu Usługodawcy oraz w celu zapewnienia zgodności działania Serwisu z obowiązującym prawem, Usługodawca za pośrednictwem Serwisu gromadzi i przetwarza niektóre dane o Użytkownikach.</p><p>W celu prawidłowego świadczenia usług, Serwis wykorzystuje i zapisuje niektóre anonimowe informacje o Usługobiorcy w plikach cookies.</p><p>Zakres, cele, sposób oraz zasady przetwarzania danych dostępne są w załącznikach do Regulaminu: <router-link to="/rodo" class="rodo-link">Obowiązek informacyjny RODO</router-link> oraz w <router-link to="/privacy-policy" class="rodo-link">Polityce prywatności</router-link>, stanowiących integralną część Regulaminu.</p><ul><li><em>Dane zbierane podczas rejestracji:</em><br>Nazwa użytkownika, adres e-mail<p>W przypadku Usługobiorców zalogowanych (posiadających konto w Serwisie), w plikach cookies zapisywanych na urządzeniu Usługobiorcy może być umieszczony identyfikator Usługobiorcy powiązany z kontem Usługobiorcy</p></li></ul></li>
        <li><h2>Prawa autorskie</h2><ul><li>Właścicielem Serwisu oraz praw autorskich do serwisu jest Usługodawca.</li><li>Część danych zamieszczonych w Serwisie są chronione prawami autorskimi należącymi do firm, instytucji i osób trzecich, niepowiązanych w jakikolwiek sposób z Usługodawcą, i są wykorzystywane na podstawie uzyskanych licencji, lub opartych na licencji darmowej.</li><li>Na podstawie Ustawy z dnia 4 lutego 1994 o prawie autorskim zabrania się wykorzystywania, kopiowania, reprodukowania w jakiejkolwiek formie oraz przetrzymywania w systemach wyszukiwania z wyłączeniem wyszukiwarki Google, Bing, Yahoo, NetSprint, DuckDuckGo, Facebook oraz LinkedIn jakichkolwiek ogłoszeń, opisów, zdjęć oraz wszelkich innych treści znajdujących się w Serwisie bez pisemnej zgody lub zgody przekazanej za pomocą komunikacji drogą elektroniczną ich prawnego właściciela.</li><li>Zgodnie z Ustawą z dnia 4 lutego 1994 o prawie autorskim ochronie nie podlegają proste informacje prasowe, rozumiane jako same informacje, bez komentarza i oceny ich autora. Autor rozumie to jako możliwość wykorzystywania informacji z zamieszczonych w serwisie tekstów, ale już nie kopiowania całości lub części artykułów o ile nie zostało to oznaczone w poszczególnym materiale udostępnionym w Serwisie.</li></ul></li>
        <li><h2>Zmiany Regulaminu</h2><ul><li>Wszelkie postanowienia Regulaminu mogą być w każdej chwili jednostronnie zmieniane przez Usługodawcę, bez podawania przyczyn.</li><li>W przypadku zmiany Regulaminu jego postanowienia wchodzą w życie natychmiast po jego publikacji dla Usługobiorców nieposiadających konta w Serwisie.</li><li>W przypadku zmiany Regulaminu jego postanowienia wchodzą w życie z 7-dniowym okresem przejściowym dla Usługobiorców posiadających konta w Serwisie zarejestrowane przez zmianą Regulaminu.</li><li>Traktuje się iż każdy Usługobiorca, kontynuujący korzystanie z Serwisu po zmianie Regulaminu akceptuje go w całości.</li></ul></li>
        <li><h2>Postanowienia końcowe</h2><ul><li>Usługodawca nie odpowiada w żaden sposób, jak tylko pozwalają na to obowiązujące przepisy prawa, za treści przekazywane i publikowane w Serwisie przez Usługobiorców, za ich prawdziwość, rzetelność, autentyczność czy wady prawne.</li><li>Usługodawca dokona wszelkich starań by usługi Serwisu były oferowane w sposób ciągły. Nie ponosi on jednak żadnej odpowiedzialności za zakłócenia spowodowane siłą wyższą lub niedozwoloną ingerencją Usługobiorców, osób trzecich czy działalnością zewnętrznych automatycznych programów.</li><li>Usługodawca zastrzega sobie prawo do zmiany jakichkolwiek informacji umieszczonych w Serwisie w wybranym przez Usługodawcę terminie, bez konieczności uprzedniego powiadomienia Usługobiorców korzystających z usług Serwisu.</li><li>Usługodawca zastrzega sobie prawo do czasowego, całkowitego lub częściowego wyłączenia Serwisu w celu jego ulepszenia, dodawania usług lub przeprowadzania konserwacji, bez wcześniejszego uprzedzania o tym Usługobiorców.</li><li>Usługodawca zastrzega sobie prawo do wyłączenia Serwisu na stałe, bez wcześniejszego uprzedzania o tym Usługobiorców.</li><li>Usługodawca zastrzega sobie prawo do dokonania cesji w części lub w całości wszelkich swoich praw i obowiązków związanych z Serwisem, bez zgody i możliwości wyrażania jakichkolwiek sprzeciwów przez Usługobiorców.</li><li>We wszelkich sprawach związanych z działalnością Serwisu należy kontaktować się z Usługodawcę korzystając z jednej z poniższych form kontaktu:<ul><li>Używając formularza kontaktowego dostępnego w Serwisie</li><li>Wysyłając wiadomość na adres e-mail: stanislawsztrajt@wp.pl, kordianj1227@gmail.com</li></ul>Kontakt przy użyciu wskazanych środków komunikacji wyłącznie w sprawach związanych z prowadzonym Serwisem.</li></ul></li>
      </ol>
    </div>
  </div>
</template>
<script>
import InfoElement from '../components/InfoElement.vue'

export default {
  components: {
    InfoElement
  }
}
</script>